### ISSUE TITLE
ONNX model incorrect!

### ISSUE THREAD

**Issue by zhi-yuan-song** [Abraham423/CenterPoint#14]
This your pfe onnx model visual dispaly.
![pfe_baseline32000 onnx](https://user-images.githubusercontent.com/58451996/185866205-d66faece-2896-4fc7-85a9-e1f734c7976d.png)
This my pfe onnx model visual dispaly 
![image](https://user-images.githubusercontent.com/58451996/185866514-4acd7487-57f3-478d-826d-97e87d04ed61.png)
I think my model is not correct. Why did my action produce an incorrect model?

**Comment by Abraham423** [comment]
You need to check the code, there must be some modification within the computation graph,  but I think this wouldn't affect the performance , you should replace the pfe output tensor name from "47" to "45", see here  https://github.com/Abraham423/CenterPoint/blob/4d70d09726050b682d27525aa65743ff106c6b9a/src/samplecenterpoint.cpp#L111

**Comment by zhi-yuan-song** [comment]
I have made changes to the c++ code and tested it,the results is correct! Thanks~
