### ISSUE TITLE
File Size Error! 1

### ISSUE THREAD

**Issue by zyxcambridge** [Abraham423/CenterPoint#5]
pointNum : {51916}[01/18/2022-11:34:29] [E] [Error] File Size Error! 1038336
[01/18/2022-11:34:29] [I] [INFO] pointNum : 51916
Success to read and Point Num  Is: 51916

**Comment by Abraham423** [comment]
if you're reading your own data, you should manage to pad point channel as 5, or your data won't be able to fit the TRT engine.
