### ISSUE TITLE
/usr/bin/ld: libpointpillars.so: undefined reference to `createNvOnnxParser_INTERNAL'

### ISSUE THREAD

**Issue by luogantt** [Abraham423/CenterPoint#7]
I try  six times ,alway has this error ,help!!!

**Comment by Natsu-Akatsuki** [comment]
try to add "target_link_libraries(pointpillars nvonnxparser)" to CMakelists.txt
@luogantt

**Comment by luogantt** [comment]
> 尝试将“target_link_libraries(pointpillars nvonnxparser)”添加到 CMakelists.txt @luogantt

thank you very very much!
