### ISSUE TITLE
performance of the tensorrt model on Waymo

### ISSUE THREAD

**Issue by forwchen** [Abraham423/CenterPoint#9]
Hello, I am trying to evaluate the performance of the provided tensorrt model on waymo validation set, but not getting reasonable numbers. The data I used is from the preprocessed version of https://github.com/tianweiy/CenterPoint, which is also *.bin format. 
I wonder if the provided model is only for evaluating the running time but not the mAP?

**Comment by Abraham423** [comment]
the model is ready for inference, maybe you should read and print the points to checkout if the bin files are valid?
